---
sitetitle: julian grove
pagetitle: about
---

* About
  Beginning in August, I'll be an Assistant Professor in the Department of Linguistics at the [[https://lin.ufl.edu/][University of Florida]].
  I'm currently a post-doctoral researcher in the [[http://factslab.io/][FACTS.lab]], directed by [[http://aaronstevenwhite.io/][Aaron Steven White]], at the [[https://www.rochester.edu/][University of Rochester]].
  Previously, I was affiliated with the [[https://gu-clasp.github.io/][Centre for Linguistic Theory and Studies in Probability]] at the [[https://www.gu.se/en][University of Gothenburg]].
  Before that, I did a PhD in [[https://linguistics.uchicago.edu/][Linguistics]] at the [[https://www.uchicago.edu/][University of Chicago]].

  I am generally interested in type-theoretic approaches to natural language semantics, which I aim to connect with Bayesian computational models of human behavior.
  I try to do this in a way that preserves the tools, like λ-calculus, that semanticists are typically used to.
  Ideally, such tools can be preserved end-to-end, and entire (computational-level) theories of semantic and pragmatic competence can be couched in the language of type theory.
  Getting this to happen means that accounts of human behavior---for example, in formal linguistics experiments---can be integrated with traditional Montagovian approaches to meaning fairly seamlessly.

  Some of my recent work has also focused on the semantics of presupposition and anaphora, and I've been investigating approaches to presupposition triggers that view them as scope-taking devices.
  I've also done experimental work focusing on ellipsis, and I was affiliated with the University of Chicago's [[http://lucian.uchicago.edu/blogs/lpl/][Language Processing Lab]], directed by [[https://lucian.uchicago.edu/blogs/mingxiang/][Ming Xiang]].

  You can email me at firstname.lastname@{gmail.com, ufl.edu}.
