project:
  type: website
  output-dir: ../docs/notes

website:
  title: "Probabilistic dynamic semantics"
  page-navigation: true
  sidebar:
    style: docked
    search: true
    contents:
    - about.qmd
    - index.qmd
    - section: "Background"
      contents:
      - background/theory-to-data.qmd
      - background/formal-pragmatics.qmd
      - background/experimental-turn.qmd
      - background/understanding-gradience.qmd
      - background/case-studies.qmd
      - background/new-frameworks.qmd
      - background/rsa.qmd
      - background/setting-stage.qmd
    - section: "Introduction to probabilistic dynamic semantics"
      contents:
      - pds-intro/pds-intro.qmd
    - section: "Gradable adjectives"
      contents:
      - adjectives/adjectives.qmd
    - section: "Factivity inferences"
      contents:
      - factivity/factivity.qmd

format:
  html:
    theme: [lux,tufte]
    highlight-style: gruvbox-dark
    css: styles.css
    toc: true
    code-tools: true

# filters:
  # - line-highlight
