---
title: "Formal pragmatics"
bibliography: ../../pds.bib
format:
  html:
    css: ../styles.css
    html-math-method: mathjax
    mathjax-config:
      loader: {load: ['[tex]/bussproofs','[tex]/bbox','[tex]/colorbox']}
      tex:
        packages: {'[+]': ['bussproofs','bbox','colorbox']}
---

::: {.hidden}
$$
\newcommand{\expr}[3]{\begin{array}{c}
#1 \\
\bbox[lightblue,5px]{#2}
\end{array} ⊢ #3}
\newcommand{\ct}[1]{\bbox[font-size: 0.8em]{\mathsf{#1}}}
\newcommand{\updct}[1]{\ct{upd\_#1}}
\newcommand{\abbr}[1]{\bbox[transform: scale(0.95)]{\mathtt{#1}}}
\newcommand{\pure}[1]{\bbox[border: 1px solid orange]{\bbox[border: 4px solid transparent]{#1}}}
\newcommand{\return}[1]{\bbox[border: 1px solid black]{\bbox[border: 4px solid transparent]{#1}}}
\def\P{\mathtt{P}}
\def\Q{\mathtt{Q}}
\def\True{\ct{T}}
\def\False{\ct{F}}
\def\ite{\ct{if\_then\_else}}
\def\Do{\abbr{do}}
$$
:::

### Dynamic semantics

One of the major success stories of formal semantics has been its ability to model the dynamics of conversation.
Since the eighties, which gave rise to foundational frameworks such as, e.g., discourse representation theory [@kamp_theory_1981] and file-change semantics [@heim_semantics_1982],*dynamic* semantics has been concerned with aspects of interpretation that both depend on earlier parts of a discourse and inform later parts.
The interpretations of pronouns in one part of a discourse my depend on the non-determinism produced by an indefinite noun phrase in some earlier part, for example.

(@ex-indef-pronoun) Some linguist walked in. They gave a lecture.

In (@ex-indef-pronoun), the interpretation of the pronoun *they* co-varies with the interpretation of the noun phrase *some linguist*;
as a result, (@ex-indef-pronoun) is true just in case there is a linguist who walked in and gave a lecture.
Such cross-sentential co-variation in the face of non-determinism of the kind introduced by the indefinite has been modeled in various dynamic frameworks.
What such frameworks tend to have in common is that they keep track of some notion of a *state*.
The framework of @heim_semantics_1982, for instance, regards this state as (effectively) an assignment function, which conveniently keeps track of the possible referents of indefinite noun phrases and pronouns.

Different frameworks differ in how they manage states.
Approaches in the style of @groenendijk_dynamic_1991 and @muskens_combining_1996, for instance, treat sentence meanings as relations on states, or equivalently, as functions from input states to sets of output states (those to which the input state is related);
i.e., functions of type $σ → σ → t$, where $σ$ is the type of states (whatever that happens to be).
If the state of a discourse keeps track of entities introduced by indefinite noun phrases, then the first sentence of (@ex-indef-pronoun) might be assigned the interpretation in (@ex-indef-interp), while the second sentence might be assigned the interpretation in (@ex-pronoun-interp).

(@ex-indef-interp) $λs.\{ x{::}s^{\prime} ∣ s^{\prime} = s ∧ \ct{ling}(x) ∧ \ct{walk}(x)\}$

(@ex-pronoun-interp) $λs.\{ s^{\prime} ∣ s^{\prime} = s ∧ \ct{lecture}(\ct{sel}(s))\}$

Here we use the state-modifying notation of @de_groote_towards_2006:
`$x{::}s$' is meant to denote the result of updating $s$ with the entity $x$, while $\ct{sel}(s)$ is some way of selecting an entity from the state $s$.^[Thus for the purposes of the example, we're eschewing the variable/register-based systems of @groenendijk_dynamic_1991 and @muskens_combining_1996.]
Thus the first sentence of (@ex-indef-pronoun) is interpreted as a function that non-deterministically modifies input states by introducing a new entity (in particular, a linguist who walked in), while the second sentence is interpreted as a function from an input state to the singleton set containing that state or to the empty set, as according to whether an entity can be selected from that input state which gave a lecture.

### Enriching the state

Much work has built on these ideas by enriching the notion of a state to countenance broader aspects of the structure of discourse.
For example, the question under discussion [QUD, @roberts_information_2012;@ginzburg_dynamics_1996]---the question whose resolution is the goal of a given discourse---along with the common ground---the set of propositions mutually taken for granted among discourse participants [@stalnaker_assertion_1978]---are incorporated into a formal definition of the *context* of a given discourse by @farkas_reacting_2010.
In addition to the common ground and a stack of QUDs, @farkas_reacting_2010 incorporate into their representation of context the notion of a *projected set*.
These are sets of possible new common grounds which are updated by new assertions and questions, and which must be accepted before the common ground itself is updated.

As we'll see in [the next module](/pds-intro/overview.html), a flexible notion of state that incorporates representations of both the common ground and the QUD will be crucial for the success of PDS.
